databases:
  - name: BBQ
    plan: free

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BBQ
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free